services:
  server:
    build: ./server
    image: mcp-weather-server:latest
    ports:
      - "8017:8017"
    restart: unless-stopped

  bridge:
    build: ./bridge
    image: mcp-weather-bridge:latest
    ports:
      - "8080:8080"
    environment:
      MCP_UPSTREAM_URL: "http://server:8017/mcp"
      # API_KEY: "set-a-strong-key"   # (ถ้าต้องการ)
    depends_on:
      - server
    restart: unless-stopped
